project:
  type: website
  output-dir: docs
  
website:
  page-navigation: true
  title: "Yucheng Chen"
  site-url: https://wangyicyc.github.io
  favicon: images/site-logo.png
  repo-url: https://wangyicyc.github.io/YuchengChen.github.io/
  repo-actions: [edit, issue]
  
  page-footer:
    left: |
      © 2026 Yucheng Chen<br>
      All rights reserved
    right: |
      Made with [Quarto](https://quarto.org/)<br>
    
  navbar: 
    background: "#4361ee"
    search: true
    logo: images/site-logo.png
    logo-alt: "Yucheng Chen"
    right: 
      - text: "Resume"
        menu:
          - text: "English"
            href: English.qmd
          - text: "中文"
            href: Chinese.qmd
      - text: "Portfolio"
        menu:
          - text: "English"
            href: portfolio.qmd
          - text: "中文"
            href: portfolio-zh.qmd
      - icon: github
        href: https://github.com
      - icon: envelope
        href: mailto:wangyi1113795069@163.com

format:
  html:
    theme: styles.scss
    toc: true            # 启用目录
    toc-position: right  # 将目录放置在页面的右侧
    toc-depth: 3         # 设置目录的深度，数字越大，目录越详细
